### ISSUE TITLE
Sorting in the combobox autocomplete seems wrong off

### ISSUE THREAD

**Issue by KeetonMartin** [KeetonMartin/routerunner#5]
See screenshot: note that San Francisco should almost certainly be the top hit here
<img width="647" alt="Screenshot 2023-03-21 at 1 06 57 AM" src="https://user-images.githubusercontent.com/25427567/226523446-0223c72b-19b8-4226-aa17-ff67dbf2153c.png">

**Comment by ThomasCarney315** [comment]
Hey, @KeetonMartin. I submitted a pull request that solved the issue in my local test. This is my first real issue/pull request. all good?

**Comment by KeetonMartin** [comment]
@ThomasCarney315 This is great work. Thanks! Feel free to fix or file any more issues you find.
